sudo: false
language: node_js
node_js:
  #  - 6
  - 7
  - 8
  - stable

cache:
  bundle: true
  directories:
    - node_modules

script:
  - npm test -- --coverage
after_script:
  - npm install codecov --no-save
  - codecov --token=$CODECOV_TOKEN
